version: "3"
services:
  
  nginx:
    container_name: cockpit-nginx
    build:
      context: .
      target: nginx
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./cockpit-core/:/var/www/html
      # - ./logs/nginx:/var/log/nginx/
    depends_on:
      - php

  php:
    container_name: cockpit-php
    build:
      context: .
      target: php
    networks:
      - internal
    volumes:
      - ./cockpit-core/:/var/www/html
      # - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    name: cockpit-net
    driver: bridge